# Generated by Django 4.2.3 on 2023-07-13 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='Base description', max_length=100),
        ),
    ]
